language: python
python:
  - "3.6"
install:
  - pip install .
  - pip install nose coverage
  - pip install coveralls
script:
  - python setup.py nosetests --with-coverage --cover-package pypiview

after_success:
  coveralls